### ISSUE TITLE
Processes list is empty because of an error during reading an application .desktop file

### ISSUE THREAD

**Issue by coreybruce** [hakandundar34coding/system-monitoring-center#171]
Hi there I am having a issue recently where I can no longer see my system processors after a few updates. I am using Manjaro Gnome on my desktop but on my laptop it's fine on the same OS.

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/8393780/87b423ac-7156-4149-a916-738be0193a90)

**Comment by hakandundar34coding** [comment]
How did you install the application? Flatpak or native?

Can you run the application by using terminal and share the errors?
Command:

- For native installations: `system-monitoring-center`
- For Flatpak installation: `flatpak run io.github.hakandundar34coding.system-monitoring-center`

Can you share a screenshot of the System tab of the application?

**Comment by coreybruce** [comment]
> How did you install the application? Flatpak or native?
> 
> Can you run the application by using terminal and share the errors? Command:
> 
>     * For native installations: `system-monitoring-center`
> 
>     * For Flatpak installation: `flatpak run io.github.hakandundar34coding.system-monitoring-center`
> 
> 
> Can you share a screenshot of the System tab of the application?

Native from the AUR and sure

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/8393780/e5875982-d645-4e8c-84b5-a51fac3cdbfe)

**Comment by hakandundar34coding** [comment]
Can you run the application by using the following command, open Processes tab and share the errors?
`system-monitoring-center`

**Comment by coreybruce** [comment]
> Can you run the application by using the following command, open Processes tab and share the errors? `system-monitoring-center`

Yep there seems to be some sort of issue, at first it doesn't show any  error logs until  I click on processors than I see this error message in the terminal.

```
system-monitoring-center                                         ✔ 
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 926, in processes_initial_func
    application_exec_list, application_icon_list, application_type_list = self.application_exec_icon_type_list()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1521, in application_exec_icon_type_list
    with open("/usr/share/applications/" + application, encoding="utf-8") as reader:
PermissionError: [Errno 13] Permission denied: '/usr/share/applications/openbor.desktop'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1138, in processes_loop_func
    if process_name in application_exec_list:                                         # Use process icon name from application file if process name is found in application exec list.
NameError: name 'application_exec_list' is not defined
^C
```

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated. The application may be updated in:

- Flathub in about 4 hours
- Other repositories in about a few days

I will close this issue. But you can write additional comments.

**Comment by coreybruce** [comment]
Yep confirmed fixed now, thank you!
