### ISSUE TITLE
Empty processes list - how to get fixed version?

### ISSUE THREAD

**Issue by w-sky** [hakandundar34coding/system-monitoring-center#179]
Hello, I just discovered System Monitoring Center for the first time and I like it … but the Processes list is empty. Below is the shell output. I have read that this bug was fixed recently but I got 2.14.0 from Flathub.org (on Ubuntu 22.04) which does not seem to be the most recent version? Or is it another bug?

```
w-sky@Abook:~$ flatpak run io.github.hakandundar34coding.system-monitoring-center
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 724384-724385: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 724385-724386: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 724385-724386: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 724384-724385: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 724370-724371: invalid continuation byte
^C
```

**Comment by w-sky** [comment]
PS: The error messages start as soon as I open the Processes tab and they also stop when I open another tab.

**Comment by hakandundar34coding** [comment]
Did you check updates from Flatpak? Is the latest version installed?

The application is updated a few hours ago. The version number did not change. Code changes are added.

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

- Open `Common.py` file in the installation directory
- Go to line `919`
- Write `"utf-8"` in paranthesis of `decode`
- Save file
- Run the application by using this command: `flatpak run io.github.hakandundar34coding.system-monitoring-center` or run `system-monitoring-center` command for native installation
- Open Processes tab and check terminal output for errors

End of the line should be like:
`...stdout.decode("utf-8").strip()`

**Comment by w-sky** [comment]
Yes I got the updated version. Then I searched some time to find out the Flatpak installation location and locate the file and line number, but it was already exactly as you wrote above.
The error messages are slightly different now:

```
$ flatpak run io.github.hakandundar34coding.system-monitoring-center
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 715273-715274: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 715297-715298: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 715297-715298: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1089, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 919, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 715297-715298: invalid continuation byte
```

**Comment by hakandundar34coding** [comment]
Can you remove `"utf-8"` and add `, universal_newlines=True` after `stderr=subprocess.PIPE` in line 919 in Common.py file?

End of the file have to be like:
`...stderr=subprocess.PIPE, universal_newlines=True)).stdout.strip()`

**Comment by hakandundar34coding** [comment]
You can update the application by using Flatpak. Are there any errors when the application is run by using terminal?

**Comment by w-sky** [comment]
Yes. I just updated, then started in shell… no error messages when opening any other tab. As soon as I open processes tab these messages come and then repeat as long as tab opened:

```
flatpak run io.github.hakandundar34coding.system-monitoring-center 
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1092, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 916, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)).stdout.strip()
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2041, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.10/subprocess.py", line 1029, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 545087-545088: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1092, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 916, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)).stdout.strip()
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2041, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.10/subprocess.py", line 1029, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 545087-545088: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1092, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 916, in processes_information
    cat_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)).stdout.strip()
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2041, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.10/subprocess.py", line 1029, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 545073-545074: invalid continuation byte
[...]
```

**Comment by hakandundar34coding** [comment]
What is the system language?

------------------------------------

Can you follow the following steps?

- Add the following line after line `916` in `Common.py` file (the line starts with 4 spaces):
    `    print((subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout)`

- Run the following command, open Processes tab and close the application just after opnening Processes tab (otherwise, output file may be very large):
    `flatpak run io.github.hakandundar34coding.system-monitoring-center > smc_process_out.txt`

- Upload `smc_process_out.txt` file.

The code have to be like:
![smc_processes_code](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/dbe33cf1-688b-4183-8d97-33172739434c)

**Comment by hakandundar34coding** [comment]
After following the steps in [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/179#issuecomment-1574911814) comment, can you follow these steps?

- Update the application by using Flatpak
- Run the application by using terminal and open Processes tab
- Share the terminal output.

**Comment by w-sky** [comment]
Hello, I just got the most recent update from Flatpak (2.14.0) and this is the shell output when I open the processes tab:

```
flatpak run io.github.hakandundar34coding.system-monitoring-center 
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 1120, in read_process_information
    cat_output = cat_output.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 532532-532533: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1092, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 890, in processes_information
    cat_output_split, global_time, global_cpu_time_all = read_process_information(process_list)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 1123, in read_process_information
    cat_output = cat_output.decode(system_encoding).strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 532532-532533: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 1120, in read_process_information
    cat_output = cat_output.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 532532-532533: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1092, in processes_loop_func
    processes_data_dict = Common.processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, processes_data_dict_prev, system_boot_time, username_uid_dict)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 890, in processes_information
    cat_output_split, global_time, global_cpu_time_all = read_process_information(process_list)
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 1123, in read_process_information
    cat_output = cat_output.decode(system_encoding).strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 532532-532533: invalid continuation byte
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 1120, in read_process_information
    cat_output = cat_output.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 532532-532533: invalid continuation byte

[repeating]
```

**Comment by w-sky** [comment]
PS: If I let it running for a while, the "positions" sometimes change to `532548-532549` but then back to `532532-532533`. Apart from that, always the same message. Don't know if this might give a clue.

**Comment by hakandundar34coding** [comment]
Probably, there are some characters that are not decoded by default. The numbers that you wrote are character positions.

The command output is required for finding these characters.
 
Here is a simpler way for getting this output:

- Download the test code: [smc_process_test.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/11663100/smc_process_test.txt)
- Change the file extension (new name: `smc_process_test.py`)
- Open terminal in the same directory
- Run this command: `python3 ./smc_process_test.py > smc_process_output.txt`
- It will generate `smc_process_output.txt` file that contains process information
- Upload the output file
- Share the position numbers or the full error message on the terminal application

**Comment by hakandundar34coding** [comment]
Process [information](https://github.com/hakandundar34coding/system-monitoring-center/issues/179#issuecomment-1578336783) is required for fixing this bug.
I will close this issue. But you can write comments.

**Comment by w-sky** [comment]
Okay so one certain process is causing System Monitoring Center to fail? I tested by starting SMC right after rebooting – processes list working! – but as soon as I start Google Chrome (/opt/google/chrome/chrome), the list freezes. When I close Chrome, it's working again.

Chrome indeed creates a lot of sub tasks with unusual command line arguments. Here I attached one cmdline from /proc/{processid}/cmdline (where {processid} was just one of the many Chrome tasks). It can not even be displayed by my text editor and fails to decode with either UTF-8, UTF-16 or ISO.

Should I open a new issue? 

[cmdline.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/11779119/cmdline.txt)

**Comment by hakandundar34coding** [comment]
- Can you find the same process on other system monitors (run them by using terminal)?
- What is shown as tooltip when you move mouse arrow on to this process?
- What is shown when you open properties window (open right click menu and select Properties)?
- Are there any errors/warnings on the terminal application?

Note: Can you share cmdline file of the process if the output is changed?

----------------------------------------

The source code is updated. You can follow these steps for testing it:
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open terminal in `src` folder
- Run the following command: `python3 ./run_from_source.py`
- Open Processes tab, check process list and terminal output for errors/warnings

Details of the change:
Characters that are not decoded are removed and shown on Processes tab. Because, row heights are changed and there are warnings on the terminal output of System Monitoring Center, if these characters are shown without decoding. During the tests, GTK toolkit could not show these characters (empty process tooltips were shown).

**Comment by hakandundar34coding** [comment]
The application is upated (v2.16.0).
I will close the issue. But you can write comments about [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/179#issuecomment-1596009793) comment or if there are problems about showing/updating processes.

**Comment by w-sky** [comment]
For your info, I reported this what seems to be a Chrome bug to what I think is the official bug reporting system for Google Chrome at https://bugs.chromium.org/p/chromium/issues/detail?id=1457893

But since 20 days no one has looked into it.

**Comment by hakandundar34coding** [comment]
Does Processes tab work?
Are there any errors?

**Comment by w-sky** [comment]
Yes, no problem in System Monitoring Center with that any more! Chrome still has this bogus command lines in its tasks, but SMC works fine with them.
I can even see the command lines at process details, and the invalid characters are shown as letters and hex representation symbols. Thanks a lot for working on this!
