### ISSUE TITLE
Performance, Processes, Users tabs are not refreshed (error when getting process status)

### ISSUE THREAD

**Issue by badcast** [hakandundar34coding/system-monitoring-center#194]
System cores changed to 
```bash 
sudo chcpu -d 1,2,3,4,5,6,7 #more cores state to offline
```
then  error log from system-monitoring-center
 ```bash 
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 976, in loop_func
    rows_data_dict = Libsysmon.get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, self.rows_data_dict_prev, self.system_boot_time, self.username_uid_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 514, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 1124, in main_gui_tab_loop
    Processes.loop_func()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 976, in loop_func
    rows_data_dict = Libsysmon.get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, self.rows_data_dict_prev, self.system_boot_time, self.username_uid_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 514, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 976, in loop_func
    rows_data_dict = Libsysmon.get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, self.rows_data_dict_prev, self.system_boot_time, self.username_uid_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 514, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Users.py", line 282, in loop_func
    rows_data_dict = Libsysmon.get_users_information(self.rows_data_dict_prev, self.system_boot_time)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 3449, in get_users_information
    processes_data_dict = get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, processes_data_dict_prev, system_boot_time, username_uid_dict)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 514, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Users.py", line 282, in loop_func
    rows_data_dict = Libsysmon.get_users_information(self.rows_data_dict_prev, self.system_boot_time)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 3449, in get_users_information
    processes_data_dict = get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, processes_data_dict_prev, system_boot_time, username_uid_dict)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 514, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 976, in loop_func
    rows_data_dict = Libsysmon.get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, self.rows_data_dict_prev, self.system_boot_time, self.username_uid_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 514, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
 ```

screens for overview 
![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/53096900-35a9-4391-85d3-a07d65fe3980)

![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/c682e632-210e-46fe-8f34-5c03b33afc47)

**Comment by hakandundar34coding** [comment]
What is your kernel version?

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

If you are using SMC v2.18.2:
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and copy `Libsysmon.py` file in the `src` folder
- Paste it to `src` folder in installation directory of the application
- Run the application by using terminal
- Check tabs and share errors in terminal output

If you are using another version:
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open `src` folder
- Run the application by using this command: `python3 ./run_from_source.py`
- Check tabs and share errors in terminal output

**Comment by badcast** [comment]
> What is your kernel version?


```
kernel is latest ZEN: 6.4.3-zen1-2-zen 
```

**Comment by badcast** [comment]
> Can you follow these steps?
> 
> If you are using SMC v2.18.2:
> 
>     * Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
> 
>     * Extract it and copy `Libsysmon.py` file in the `src` folder
> 
>     * Paste it to `src` folder in installation directory of the application
> 
>     * Run the application by using terminal
> 
>     * Check tabs and share errors in terminal output
> 
> 
> If you are using another version:
> 
>     * Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
> 
>     * Extract it and open `src` folder
> 
>     * Run the application by using this command: `python3 ./run_from_source.py`
> 
>     * Check tabs and share errors in terminal output

Updated to latest (AUR) 
Repeat command 
```bash
sudo chcpu -d 1,2,3,4,5,6,7 #more cores state to offline
```
```
LANG= system-monitoring-center

(python:357121): Adwaita-WARNING **: 00:26:42.513: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1210, in loop_func
    rows_data_dict = Libsysmon.get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, self.rows_data_dict_prev, self.system_boot_time, self.username_uid_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 543, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 1131, in main_gui_tab_loop
    Processes.loop_func()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1210, in loop_func
    rows_data_dict = Libsysmon.get_processes_information(process_list, processes_of_user, cpu_usage_divide_by_cores, detail_level, self.rows_data_dict_prev, self.system_boot_time, self.username_uid_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 543, in get_processes_information
    status = process_status_dict[stat_file_split[-50]]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'P'
```

screen for overview: 

![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/ba6e0bf7-063c-4424-8829-0f226703d9ad)
![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/3bad90e8-68a1-4e41-b1eb-eef93a420bce)

**Comment by hakandundar34coding** [comment]
SMC v2.8.2 in the repositories does not contain the latest changes.
Can you run the application from source code?

- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open `src` folder
- Run the application by using this command: `python3 ./run_from_source.py`
- Check tabs and share errors in terminal output

**Comment by badcast** [comment]
> SMC v2.8.2 in the repositories does not contain the latest changes. Can you run the application from source code?
> 
>     * Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
> 
>     * Extract it and open `src` folder
> 
>     * Run the application by using this command: `python3 ./run_from_source.py`
> 
>     * Check tabs and share errors in terminal output

Fine! There are no errors.

**Comment by badcast** [comment]
What do you suggest to do next?

**Comment by hakandundar34coding** [comment]
Option 1:
You can copy `Libsysmon.py` file (in the source code) into `src` folder in the installation directory of the application.

Option 2:
You can wait new version of SMC (a few days).

**Comment by hakandundar34coding** [comment]
The application is updated. SMC v2.18.3 can be installable by using:

- Flatpak in about 4 hours
- Other repositories in about a few days/weeks


I will close this issue. But you can open a new one for bugs, new features, etc.
