### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by lorenzo0932** [hakandundar34coding/system-monitoring-center#236]
Problem: Crash at start
Aspected Behavor: Won't crash

If started from terminal it will return the follow errors:
```
flatpak run io.github.hakandundar34coding.system-monitoring-center                                                                                                              (base) 

(python:2): Gtk-WARNING **: 10:05:15.203: Unknown key gtk-modules in /home/lorenzo/.var/app/io.github.hakandundar34coding.system-monitoring-center/config/gtk-4.0/settings.ini
Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Main.py", line 18, in on_activate
    from .MainWindow import MainWindow
  File "/app/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 14, in <module>
    from .Performance import Performance
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Performance.py", line 2, in <module>
    import cairo
  File "/home/lorenzo/.local/lib/python3.11/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/lorenzo/.local/lib/python3.11/site-packages/cairo/_cairo.cpython-311-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
```

What i've try:
- Uninstall and remove user data
- Reinstall the required flatpak runtime

System specification: 
```
neofetch                                                         (base) 
             .',;::::;,'.                lorenzo@ryzen-di-lorenzo 
         .';:cccccccccccc:;,.            ------------------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora release 38 (Thirty Eight 
    .:cccccccccccccccccccccccccc:.       Host: MS-7B79 4.0 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.5.7-200.fc38.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 16 hours, 18 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2657 (rpm), 93 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.15 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2560x1080 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 44.5 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: adw-gtk3 [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Papirus-black [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: BlackBox 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: AMD Ryzen 5 3600 (12) @ 4.200GHz 
:cccccccccccccccccccccccccccc:'.         GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT 
.:cccccccccccccccccccccc:;,..            Memory: 13335MiB / 32001MiB 
  '::cccccccccccccc::;,.
```

**Comment by hakandundar34coding** [comment]
The application is tested on the same distribution on virtual machine. There was no crash during start of the application. It looks like there is a problem about pycairo dependency. This dependency is included in gnome desktop environment platform in Flatpak environment.
